/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBridgeAssist, IBridgeAssistInterface } from "../IBridgeAssist";

const _abi = [
  {
    inputs: [],
    name: "TOKEN",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "limitPerSend_",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "feeWallet_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "feeSend_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feeFulfill_",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "relayers_",
        type: "address[]",
      },
      {
        internalType: "uint256",
        name: "relayerConsensusThreshold_",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBridgeAssist__factory {
  static readonly abi = _abi;
  static createInterface(): IBridgeAssistInterface {
    return new utils.Interface(_abi) as IBridgeAssistInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBridgeAssist {
    return new Contract(address, _abi, signerOrProvider) as IBridgeAssist;
  }
}
